dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      
script:
  #- export CXX=/usr/local/clang-5.0.0/bin/clang
  #- export CC=/usr/local/clang-5.0.0/bin/clang
  - export CXX=/usr/bin/g++-6 
  - export CC=/usr/bin/gcc-6
  - ls
  - cd cryptoTools/thirdparty/linux
  - bash all.get
  - cd ../../..
  - cmake .
  - cmake --build . -- -j2
